name: Compile App (PR)

on:
  pull_request:

jobs:
  pack:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Compile
        run: |
          npm run build:ssr
          apt-get update && apt-get install -y zip
          cd dist/ && zip -r build.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: compile-output.zip
          path: dist/build.zip
          retention-days: 14