name: Fix Base Branch

on:
  push:
    branches:
      - master
      - stage

  pull_request:
    branches:
      - master
      - stage

jobs:
  fix:
    name: Change Pull Request Base Branch
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.x
        id: fix_pr_branch
        with:
          route: PATCH /repos/{repo}/pulls/{event_id}
          repo: ${{ github.repository }}
          event_id: ${{ github.event.number }}
          base: dev

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
